const TOPIC_SUBMISSION_ALLOWED_MIME_TYPES = [
  "application/pdf",
  "image/jpeg",
  "image/png",
];

const TOPIC_SUBMISSION_MAX_FILE_SIZE_MB = 10;
const TOPIC_SUBMISSION_MAX_FILE_SIZE_BYTES =
  TOPIC_SUBMISSION_MAX_FILE_SIZE_MB * 1024 * 1024;

module.exports = {
  TOPIC_SUBMISSION_ALLOWED_MIME_TYPES,
  TOPIC_SUBMISSION_MAX_FILE_SIZE_MB,
  TOPIC_SUBMISSION_MAX_FILE_SIZE_BYTES,
  ACTIVITY_SUBMISSION_ALLOWED_MIME_TYPES: TOPIC_SUBMISSION_ALLOWED_MIME_TYPES,
  ACTIVITY_SUBMISSION_MAX_FILE_SIZE_MB: TOPIC_SUBMISSION_MAX_FILE_SIZE_MB,
  ACTIVITY_SUBMISSION_MAX_FILE_SIZE_BYTES: TOPIC_SUBMISSION_MAX_FILE_SIZE_BYTES,
};
